@extends('layout.master')
@section('title', 'Dynamic Presentation')

 

@section('content')

    {{-- Slide 1 --}}
    <div class="slide flex flex-col items-center justify-between h-[50%]">
        <div class="title stroke">
            <h2>Children, do you remember what makes an aeroplane
                stay on the ground?</h2>
        </div>
        <p class="note">Note: Guide children to reflect and share their answers.</p>
    </div>

    {{-- Slide 2 --}}
    <div class="slide hidden flex flex-col items-center justify-center">
        <h2 class="title stroke">Just like everything on Earth, <br>
            aeroplanes stay on the ground because of gravity.</h2>
    </div>

    {{-- Slide 3 --}}
    <div class="slide hidden  flex flex-col items-center">
        <img src="{{ asset('assets/images/K2/aero/aero1/a3.png') }}" />
        <h2 class="title stroke">Gravity is the force that pulls everything to the ground.</h2>
    </div>

    {{-- slide 4 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <div class="flex items-center gap-5">
            <img src="{{ asset('assets/images/K2/aero/aero1/a46.png') }}" />
            <img src="{{ asset('assets/images/K2/aero/aero1/a7.png') }}" />
        </div>
        <h2 class="title stroke">Weight comes from the force of gravity pulling down objects.</h2>
    </div>

    {{-- Slide 5 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <img src="{{ asset('assets/images/K2/aero/aero1/a40.png') }}" />
        <h2 class="title stroke">An aeroplane has to overcome its weight <br>
            to lift up from the ground.</h2>
    </div>

    {{-- slide 6 --}}
    <div class="slide hidden flex flex-col items-center justify-center">
        <img src="{{ asset('assets/images/K2/aero/aero1/a42.png') }}" />
        <h2 class="title stroke">Lift is a force that pushes something up.</h2>
    </div>

    {{-- slide 7 --}}
    <div class="slide hidden flex flex-col items-center justify-center">
        <img src="{{ asset('assets/images/K2/aero/aero1/a43.png') }}" />
        <h2 class="title stroke">The force of lift is generated by the wings.</h2>
    </div>

    {{-- slide 8 --}}
    <div class="slide hidden flex flex-col items-center justify-center">
        <img src="{{ asset('assets/images/K2/aero/aero1/a12.png') }}" />
        <h2 class="title stroke">The shape of the aeroplane wings plays an important <br>
            part in generating lift.</h2>
    </div>

    {{-- slide 9 --}}
    <div class="slide hidden flex flex-col items-center justify-center">
        <img src="{{ asset('assets/images/K2/aero/aero1/a44.png') }}" />
        <h2 class="title stroke">This shape is called an aerofoil.</h2>
    </div>

    {{-- slide 10 --}}
    <div class="slide hidden flex flex-col items-center justify-center">
        <img src="{{ asset('assets/images/K2/aero/aero1/a41.png') }}" />
        <h2 class="title stroke">The heavy aeroplane will require a strong force of lift
            to take off into the sky.</h2>
    </div>

    {{-- slide 11 --}}
    <div class="slide hidden flex flex-col items-center justify-center">
        <img src="{{ asset('assets/images/K2/aero/aero1/a22.png') }}" />
        <h2 class="title stroke">But how do aeroplanes move forward after taking off?</h2>
        <p class="note">Note: Encourage children to share their answers.</p>
    </div>

    {{-- slide 12 --}}
    <div class="slide hidden  flex flex-col items-center h-[60%] justify-between ">
        <h2 class="!text-white title stroke">Hands-on Time 1</h2>
        <div class="self-start text-start">
            <h2 class="title stroke">Mission: <br>
                Let's find out what helps an aeroplane move forward.</h2>
        </div>
    </div>

    {{-- slide 13 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <div class="self-start text-start">
            <h2 class="title stroke">Steps: <br>
                1.Observe and talk about the setup.</h2>
        </div>
        <img src="{{ asset('assets/images/K2/aero/aero1/a23.png') }}" />
        <p class="note text-center">Note: Guide children to identify the items used for this setup.</p>
    </div>

    {{-- Slide 14 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <div class="self-start text-start">
            <h2 class="title stroke">Steps: <br>
                2. Pull the balloon as close to the chair as possible.</h2>
        </div>
        <img src="{{ asset('assets/images/K2/aero/aero1/a24.png') }}" />
    </div>

    {{-- Slide 15 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <div class="self-start text-start">
            <h2 class="title stroke">Steps:<br>
                3. Release the clip but press onto the mouth of the balloon so
                that air will not escape</h2>
        </div>
        <img src="{{ asset('assets/images/K2/aero/aero1/a25.png') }}" />
    </div>

    {{-- Slide 16 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <div class="self-start text-start">
            <h2 class="title stroke">Steps: <br>
                4. Release the mouth of the balloon and share your observation </h2>
        </div>
        <img src="{{ asset('assets/images/K2/aero/aero1/a23.png') }}" />
        <p class="note text-center">Note: The string needs to be taut before the balloon is released.</p>
    </div>

    {{-- Slide 17 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <video id="video1" class="pointer-events-none">
            <source src="{{ asset('assets/images/K2/aero/aero1/211.mp4') }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <h2 class="title stroke">As the air rushes out of the balloon, it creates a pushing
            force called thrust. This force pushes the balloon to move
            forward and fly across the string.</h2>
        <!-- Video Trigger Button -->
        <div onclick="toggleVideo('video1')"
            class="absolute top-1/2 right-[-10vw] z-30 -translate-y-1/2 video-btn cursor-pointer rounded-[30px] bg-sky-500 shadow-[3px_4px_7.8px_rgba(0,0,0,0.25)] shadow-[inset_3px_-4px_4px_rgba(0,0,0,0.25)] outline outline-1 outline-cyan-900"
            onclick="toggleVideo('video1')">
            <img src="/assets/images/pptimages/Vector4.png" class="absolute top-[6px] left-[8px] h-10 w-20" />
            <div class="absolute top-[10px] left-[19.74px] h-3.5 w-5 bg-white"></div>
            <img class="absolute top-[24px] left-[22px] h-14 w-14" src="/assets/images/pptimages/play.png" />
        </div>
    </div>

    {{-- Slide 18 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <img src="{{ asset('assets/images/K2/aero/aero1/a47.png') }}" />
        <h2 class="title stroke">Thrust is the force that pushes the aeroplane forward.</h2>
    </div>

    {{-- Slide 19 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <h2 class="title stroke">Now, imagine you are trying to run forward but someone
            is pulling back your shirt in the opposite direction.
            Will it be hard to keep moving forward? Why?</h2>
        <p class="note text-center">Note: Encourage children to share their answers.</p>
    </div>

    {{-- slide 20  --}}
    <div class="slide hidden  flex flex-col items-center h-[50%] justify-between ">
        <h2 class="!text-white title stroke">Hands-on Time 2</h2>
        <div class="text-start self-start">
            <h2 class="title stroke">Mission: <br>
                Let's find out what could keep an aeroplane from
                moving forward.</h2>
        </div>
    </div>

    {{-- Slide 21 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <div class="self-start text-start">
            <h2 class="title stroke">Steps: <br>
                1.Observe and talk about the setup.</h2>
        </div>
        <img src="{{ asset('assets/images/K2/aero/aero1/a27.png') }}" />
        <p class="note">Note: Guide children to identify the items used for this setup.</p>
    </div>

    {{-- Slide 22 --}}
    <div class="slide hidden  flex flex-col items-center justify-start  ">
        <div class="self-start text-start">
            <h2 class="title stroke">Steps: <br>
                2. Pull the 2 balloons as close to the chair as possible.
                Release the balloons simultaneously. Observe the distance
                travelled by both balloons. Share and discuss your
                observation.</h2>
        </div>
        <img src="{{ asset('assets/images/K2/aero/aero1/a27.png') }}" />
    </div>

    {{-- Slide 23 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <video id="video2" class="pointer-events-none">
            <source src="{{ asset('assets/images/K2/aero/aero1/212.mp4') }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <h2 class="title stroke">The balloon with the cone shape is able to move further
            as it has less drag compared to the one with the round plate.</h2>
        <!-- Video Trigger Button -->
        <div onclick="toggleVideo('video1')"
            class="absolute top-1/2 right-[-10vw] z-30 -translate-y-1/2 video-btn cursor-pointer rounded-[30px] bg-sky-500 shadow-[3px_4px_7.8px_rgba(0,0,0,0.25)] shadow-[inset_3px_-4px_4px_rgba(0,0,0,0.25)] outline outline-1 outline-cyan-900"
            onclick="toggleVideo('video2')">
            <img src="/assets/images/pptimages/Vector4.png" class="absolute top-[6px] left-[8px] h-10 w-20" />
            <div class="absolute top-[10px] left-[19.74px] h-3.5 w-5 bg-white"></div>
            <img class="absolute top-[24px] left-[22px] h-14 w-14" src="/assets/images/pptimages/play.png" />
        </div>
    </div>

    {{-- Slide 24 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a48.png') }}" />
        <h2 class="title stroke">Drag is the opposing force of thrust that slows down the
            aeroplane.</h2>
    </div>

    {{-- Slide 25 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a29.png') }}" />
        <h2 class="title stroke">Look at the shape of the noses of these aircrafts.
            What do you see?</h2>
    </div>

    {{-- Slide 26 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a29.png') }}" />
        <h2 class="title stroke">The shape of the aeroplane nose is designed to reduce drag
            as it moves through air.</h2>
    </div>

    {{-- Slide 27 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a48.png') }}" />
        <h2 class="title stroke">When there is less drag, the aeroplane will be able to keep
            moving forward.</h2>
    </div>

    {{-- Slide 28 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a45.png') }}" />
        <h2 class="title stroke">These are the four forces of flight. You may also called it
            the four aerodynamic forces or the aerodynamics of flight.</h2>
    </div>

    {{-- Slide 29 --}}
    <div class="slide hidden flex flex-col items-center justify-between h-[50%]">
        <h2 class="title stroke">Now, you have learned about the aerodynamics of flight.
            Do you know what is aerodynamics?</h2>
        <p class="note">Note: Encourage children to share their answers.</p>
    </div>

    {{-- Slide 30 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a45.png') }}" />
        <h2 class="title stroke">Aerodynamics comes from the word aero (air) and dynamic
            (movement).</h2>
    </div>

    {{-- Slide 31 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a45.png') }}" />
        <h2 class="title stroke">Aerodynamics is the way air moves around things.
            Anything that moves through air is affected by aerodynamics.</h2>
    </div>

    {{-- Slide 32 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <video id="video3" class="pointer-events-none">
            <source src="{{ asset('assets/images/K2/aero/aero1/213.mp4') }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <h2 class="title stroke">Observe the movement on the aeroplane
            wing during take off</h2>
        <!-- Video Trigger Button -->
        <div onclick="toggleVideo('video1')"
            class="absolute top-1/2 right-[-10vw] z-30 -translate-y-1/2 video-btn cursor-pointer rounded-[30px] bg-sky-500 shadow-[3px_4px_7.8px_rgba(0,0,0,0.25)] shadow-[inset_3px_-4px_4px_rgba(0,0,0,0.25)] outline outline-1 outline-cyan-900"
            onclick="toggleVideo('video3')">
            <img src="/assets/images/pptimages/Vector4.png" class="absolute top-[6px] left-[8px] h-10 w-20" />
            <div class="absolute top-[10px] left-[19.74px] h-3.5 w-5 bg-white"></div>
            <img class="absolute top-[24px] left-[22px] h-14 w-14" src="/assets/images/pptimages/play.png" />
        </div>
    </div>

    {{-- Slide 33 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <video id="video4" class="pointer-events-none">
            <source src="{{ asset('assets/images/K2/aero/aero1/214.mp4') }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <h2 class="title stroke">Observe the movement on the aeroplane
            wing during landing</h2>
        <!-- Video Trigger Button -->
        <div onclick="toggleVideo('video1')"
            class="absolute top-1/2 right-[-10vw] z-30 -translate-y-1/2 video-btn cursor-pointer rounded-[30px] bg-sky-500 shadow-[3px_4px_7.8px_rgba(0,0,0,0.25)] shadow-[inset_3px_-4px_4px_rgba(0,0,0,0.25)] outline outline-1 outline-cyan-900"
            onclick="toggleVideo('video4')">
            <img src="/assets/images/pptimages/Vector4.png" class="absolute top-[6px] left-[8px] h-10 w-20" />
            <div class="absolute top-[10px] left-[19.74px] h-3.5 w-5 bg-white"></div>
            <img class="absolute top-[24px] left-[22px] h-14 w-14" src="/assets/images/pptimages/play.png" />
        </div>
    </div>

    {{-- Slide 34 --}}
    <div class="slide hidden flex flex-col items-center justify-between h-[50%]">
        <h2 class="title stroke">How is the movement of the wings different during <br>
            take off and landing? <br>
            Why do you think this happen?</h2>
        <p class="note">Note: Encourage children to discuss and share their answers.</p>
    </div>

    {{-- Slide 35 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a32.png') }}" />
        <h2 class="title stroke">Flaps and spoilers play an important role during take off and
            landing. Can you tell the function of the flaps and spoilers?
            Why are spoilers named as such?</h2>
    </div>

    {{-- Slide 36 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a50.png') }}" />
        <h2 class="title stroke">During take off, the flaps are adjusted downward to increase
            lift and reduce drag.</h2>
    </div>

    {{-- Slide 37 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a51.png') }}" />
        <h2 class="title stroke">During landing, the flaps are fully extended to
            increase both lift and drag.</h2>
    </div>

    {{-- Slide 38 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <img src="{{ asset('assets/images/K2/aero/aero1/a33.png') }}" />
        <h2 class="title stroke">The spoilers are extended to increase drag and reduce lift only
            during landing. Spoilers are used to 'spoil' the movement of air
            to slow down the aeroplane and ensure it stays on the ground.</h2>
    </div>

    {{-- Slide 39 --}}
    <div class="slide hidden flex flex-col items-center justify-center gap-y-2">
        <h2 class="title stroke">Are you able to recall the four aerodynamic forces?
            Which force should be higher for the aeroplane to take off?
            Which force should be higher to help the aeroplane move
            forward while flying in the sky?</h2>
        <p class="note">Note: Encourage children to share their answers.</p>
    </div>

    {{-- slide 40 --}}
    <div class="slide  hidden flex flex-col items-center justify-center gap-y-4">
        <h2 class=" title stroke !text-white">Learning Journal</h2>
        <div class="w-[836px] h-fit bg-cover bg-center p-[20px] flex flex-col justify-center items-center"
            style="background-image: url('{{ asset('assets/images/pptimages/dark4.png') }}');">
            <p>Label the four aerodynamic forces.</p>
            <img src="{{ asset('assets/images/K2/aero/aero1/a34.png') }}" />
        </div>
    </div>

    {{-- slide 41 --}}
    <div class="slide  hidden flex flex-col items-center justify-center gap-y-4">
        <h2 class=" title stroke !text-white">Learning Journal</h2>
        <div class="w-[836px] h-fit bg-cover bg-center p-[20px] flex flex-col justify-center items-center"
            style="background-image: url('{{ asset('assets/images/pptimages/dark4.png') }}');">
            <p>Label the aerodynamic force that should be higher for the aeroplane to take off.</p>
            <img src="{{ asset('assets/images/K2/aero/aero1/a34.png') }}" />
        </div>
    </div>

    {{-- slide 42 --}}
    <div class="slide  hidden flex flex-col items-center justify-center gap-y-4">
        <h2 class=" title stroke !text-white">Learning Journal</h2>
        <div class="w-[836px] h-fit bg-cover bg-center p-[20px] flex flex-col justify-center items-center"
            style="background-image: url('{{ asset('assets/images/pptimages/dark4.png') }}');">
            <p>Label the aerodynamic force that should be higher for the aeroplane to keep moving
                forward while flying in the sky.</p>
            <img src="{{ asset('assets/images/K2/aero/aero1/a34.png') }}" />
        </div>
    </div>

    {{-- ====================================== --}}
    {{-- Buttons --}}
    <div class="down-btn-container">
        <button
         class="doneButton">
 <img src="{{ asset('assets/images/pptimages/done.png') }}" />
        </button>
    </div>

 <div id="buttons" class="absolute  flex flex-row gap-6 ">
        <!-- Return Button -->
        <a id="returnButton">
 <img
    src="{{ asset('assets/images/pptimages/return.png') }}" />
        </a>

        <!-- Home Button -->
        <button
     id="homeButton">
            <img 
                src="{{ asset('assets/images/pptimages/home-btn.png') }}" />
        </button>

        <!-- Close Button -->
        <button id="closeButton">
           
            <img 
                src="{{ asset('assets/images/pptimages/cancel.png') }}" />
    
        </button>
    </div>

    {{-- Next Button --}}
    <div class="down-btn-container">
        <button class="cursor-pointer nextButton w-66 h-[75px] relative bg-[#F8A23A]  rounded-[30px] overflow-hidden">
            <div class="bg-white w-[27px] h-[18px] absolute top-[9px] left-[19px]"></div>
            <div class="absolute left-[8.22px] top-[3.17px] "> <img src="/assets/images/pptimages/Vector4.png" /> </div>
            <span class="flex items-center  text-white text-5xl  stroke">NEXT
            </span>
        </button>
    </div>
@endsection

@push('script')
    <script>
        // Video toggle function - har video ko separately control karta hai
        function toggleVideo(videoId) {
            const video = document.getElementById(videoId);
            if (video.paused) {
                video.play();
            } else {
                video.pause();
            }
        }

        document.addEventListener("DOMContentLoaded", () => {
            const slides = document.querySelectorAll(".slide");
            const nextButtons = document.querySelectorAll(".nextButton");
            const returnButton = document.getElementById("returnButton");
            const doneButton = document.querySelector(".doneButton");
            const infoButtons = document.querySelectorAll("[class*='info-btn'], [class*='click-btn']");

            let currentSlide = 0;
            let parentSlideIndex = null;
            let isViewingInfoSlides = false;
            let currentInfoClass = null;

            function showSlide(index) {
                slides.forEach((slide, i) => {
                    slide.classList.toggle("hidden", i !== index);
                });

                const isLastSlide = index === slides.length - 1;
                const isLastInfoSlide = isViewingInfoSlides && !hasNextInfoSlide(index);

                if (isLastSlide || isLastInfoSlide) {
                    nextButtons.forEach(btn => btn.classList.add("hidden"));
                    if (doneButton) doneButton.classList.remove("hidden");
                } else {
                    nextButtons.forEach(btn => btn.classList.remove("hidden"));
                    if (doneButton) doneButton.classList.add("hidden");
                }
            }

            function hasNextInfoSlide(currentIndex) {
                if (!currentInfoClass) return false;
                for (let i = currentIndex + 1; i < slides.length; i++) {
                    if (slides[i].classList.contains(currentInfoClass)) {
                        return true;
                    }
                }
                return false;
            }

            function getInfoClassFromButton(button) {
                const classList = Array.from(button.classList);
                const infoBtnClass = classList.find(cls => cls.startsWith('info-btn'));
                if (infoBtnClass) {
                    const number = infoBtnClass.replace('info-btn', '');
                    return 'info-slide' + number;
                }
                const clickBtnClass = classList.find(cls => cls.startsWith('click-btn'));
                if (clickBtnClass) {
                    const number = clickBtnClass.replace('click-btn', '');
                    return 'click' + number;
                }
                return null;
            }

            infoButtons.forEach((btn) => {
                btn.addEventListener("click", (e) => {
                    e.preventDefault();
                    parentSlideIndex = currentSlide;
                    isViewingInfoSlides = true;
                    currentInfoClass = getInfoClassFromButton(btn);

                    for (let i = 0; i < slides.length; i++) {
                        if (slides[i].classList.contains(currentInfoClass)) {
                            currentSlide = i;
                            showSlide(currentSlide);
                            break;
                        }
                    }
                });
            });

            nextButtons.forEach((btn) => {
                btn.addEventListener("click", () => {
                    if (currentSlide < slides.length - 1) {
                        currentSlide++;

                        while (!isViewingInfoSlides &&
                            currentSlide < slides.length &&
                            isInfoSlide(slides[currentSlide])) {
                            currentSlide++;
                        }

                        if (isViewingInfoSlides) {
                            while (currentSlide < slides.length &&
                                !slides[currentSlide].classList.contains(currentInfoClass)) {
                                currentSlide++;
                            }
                        }

                        if (currentSlide < slides.length) {
                            showSlide(currentSlide);
                        }
                    }
                });
            });

            function isInfoSlide(slide) {
                return Array.from(slide.classList).some(cls =>
                    (cls.startsWith('info-slide') && cls.match(/^info-slide\d+$/)) ||
                    (cls.startsWith('click') && cls.match(/^click\d+$/))
                );
            }

            returnButton.addEventListener("click", () => {
                if (isViewingInfoSlides && currentSlide > 0) {
                    let prevSlide = currentSlide - 1;

                    while (prevSlide >= 0 && !slides[prevSlide].classList.contains(currentInfoClass)) {
                        prevSlide--;
                    }

                    if (prevSlide >= 0 && slides[prevSlide].classList.contains(currentInfoClass)) {
                        currentSlide = prevSlide;
                        showSlide(currentSlide);
                    } else {
                        currentSlide = parentSlideIndex;
                        isViewingInfoSlides = false;
                        currentInfoClass = null;
                        parentSlideIndex = null;
                        showSlide(currentSlide);
                    }
                } else if (currentSlide > 0) {
                    currentSlide--;

                    while (currentSlide > 0 && isInfoSlide(slides[currentSlide])) {
                        currentSlide--;
                    }

                    showSlide(currentSlide);
                }
            });

            if (doneButton) {
                doneButton.addEventListener("click", () => {
                    if (isViewingInfoSlides && parentSlideIndex !== null) {
                        currentSlide = parentSlideIndex;
                        isViewingInfoSlides = false;
                        currentInfoClass = null;
                        parentSlideIndex = null;
                        showSlide(currentSlide);
                    } else {
                        window.location.href = "{{ route('Aerodynamics2Selection') }}";
                    }
                });
            }

            showSlide(currentSlide);
        });
    </script>
@endpush
